name: Ranni Contribution Graph

on:
  workflow_dispatch:
  schedule:
    - cron: "0 3 * * *"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o projeto
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar dependências
        run: pip install -r requirements.txt

      - name: Gerar gráfico da Ranni
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
        run: python scripts/generate_ranni.py

      - name: Salvar gráfico
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add generated/ranni-contributions.gif

          if git diff --cached --quiet; then
            echo "Nenhuma alteração."
          else
            git commit -m "chore: update Ranni contribution animation"
            git push
          fi
